apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-api
    spec:
      containers:
        - name: flask-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_ENV
              value: {{ .Values.env.flaskEnv }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-flask-api-secret
                  key: databaseUrl
